<a href="https://colab.research.google.com/github/preethadk11/HTML-Project-roadmap.sh-/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
def is_palindrome():
  x=int(input())
  s=str(x)
  if s==s[::-1]:
    return True
  else:
    return False

print(is_palindrome())

-121
False


##Let start it


In [ ]:
import numpy as np


In [ ]:
arr1=np.array([1,2,3,4,5],dtype=float)
print(type(arr1))
print(arr1)
print(arr1.dtype)
print(arr1.shape)#gives the value present in each dimension
print(arr1.ndim)#gives the dimesion
arr2=np.array([[[1,2],[3,4]],[[2,3],[3,4]],[[2,3],[5,6]]])
print(arr2)
print(arr2.shape)
print(arr2.ndim)
print(arr2.reshape(4,3))
print(arr2.reshape(2,3,2))


<class 'numpy.ndarray'>
[1. 2. 3. 4. 5.]
float64
(5,)
1
[[[1 2]
  [3 4]]

 [[2 3]
  [3 4]]

 [[2 3]
  [5 6]]]
(3, 2, 2)
3
[[1 2 3]
 [4 2 3]
 [3 4 2]
 [3 5 6]]
[[[1 2]
  [3 4]
  [2 3]]

 [[3 4]
  [2 3]
  [5 6]]]
3


In [ ]:
#identity matrix

In [ ]:
print(np.identity(3,dtype=int))#by default it is float
print(np.eye(3,1,dtype=int))

[[1 0 0]
 [0 1 0]
 [0 0 1]]
[[1]
 [0]
 [0]]


In [ ]:
##new parameter k


In [ ]:
np.eye(3,5,k=2,dtype=int)

array([[0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

##broadcasting
if we add 1d with 2d the smaller dimension will automatically expand to a higher dimension

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([7,8,9])
c=a+b
print(c)
print(c.shape)

[[ 8 10 12]
 [11 13 15]]
(2, 3)


In [ ]:
d=np.zeros((3,3),dtype=int)+2*0
print(d)
e=np.ones((4,4),dtype=int)*7
print(e)
np.full((3,4),4,dtype=int)

[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


array([[4, 4, 4, 4],
       [4, 4, 4, 4],
       [4, 4, 4, 4]])

##mathematical methods in numpy

In [ ]:
arr=np.array([1,2,3,4,5],dtype=int)
print(f'sum of array:{np.sum(arr)}')
print(f'product of array:{np.prod(arr)}')
print(f'largest element:{np.max(arr)}')
print(f'smallest element:{np.min(arr)}')
print(f'standard deviation:{np.std(arr)}')
print(f'varience:{np.var(arr)}')
print(f'mean:{np.mean(arr)}')
print(f'cummulative sum:{np.cumsum(arr)}')

sum of array:15
product of array:120
largest element:5
smallest element:1
standard deviation:1.4142135623730951
varience:2.0
mean:3.0
cummulative sum:[ 1  3  6 10 15]


##RANDOM METHOD

In [ ]:

np.random.rand(4)
arr=np.random.randint(1,9,size=(3,3))
print(arr)
np.random.shuffle(arr)
arr



[[1 4 6]
 [2 2 1]
 [2 5 2]]


array([[1, 4, 6],
       [2, 2, 1],
       [2, 5, 2]])

##MATRIX MANIPULATION

In [ ]:
a=np.array([[1,2,3],[4,5,6]])
print(a)
x=np.transpose(a)
print(x)
print(a.flatten())
d=np.array([1,2])
e=np.array([2,4])
print(np.vstack((d,e)))
print(np.hstack((d,e)))

[[1 2 3]
 [4 5 6]]
[[1 4]
 [2 5]
 [3 6]]
[1 2 3 4 5 6]
[[1 2]
 [2 4]]
[1 2 2 4]


In [ ]:
arr1=np.array([[1,2,3],
        [4,5,6],
        [7,8,9]])
print(arr1)
print(arr1[1,1])
print(arr1[2,0:3])
print(arr1[0:2,0:2])
print(np.where(arr1>=2,'high','low'))


[[1 2 3]
 [4 5 6]
 [7 8 9]]
5
[7 8 9]
[[1 2]
 [4 5]]
[['low' 'high' 'high']
 ['high' 'high' 'high']
 ['high' 'high' 'high']]
[[14  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[14  2  3]
 [ 4  5  6]
 [ 7  8  9]]
[[14  2  3]
 [ 4  5  6]
 [ 7  8  9]]


In [ ]:
import numpy as np

a=np.array([1,2,3])

b=a.copy()
a[0]=100
c=a.view()


print(a)
print(b)
print(c)

[100   2   3]
[1 2 3]
[100   2   3]


In [ ]:
import re
def func(s):
  new=re.sub(r'[^A-Za-z0-9]','',s).lower()
  if new==new[::-1]:
    return True
  else:
    return False

s="tab a cat"
print(func(s))

False


In [ ]:
def func(nums,target):
  lower=0
  flag=0
  upper=len(nums)-1
  while lower<=upper:
    mid=int((lower+upper)/2)
    if nums[mid]==target:
      flag+=1
      break
    elif nums[mid]<target:
      lower=mid+1
    else:
      upper=mid-1
  if flag==1:
      return mid
  else:
    return -1

nums=[-1,0,2,4,6,8]
print(func(nums,3))

-1


In [5]:
%%javascript
for(let i=1;i<=10;i++){
  console.log(i)
}

<IPython.core.display.Javascript object>

In [6]:
%%javascript
function sum(num1,num2){
  return num1+num2
}
console.log(sum(5,3));

<IPython.core.display.Javascript object>

In [7]:
%%javascript
let num=7
if (num%2==0){
  console.log("Even");
}
else{
  console.log("Odd")
}

<IPython.core.display.Javascript object>

In [8]:
%%javascript
nums=[10,20,30,40,50]
for (let i=0;i<nums.length;i++){
    console.log(nums[i])
}

<IPython.core.display.Javascript object>

In [14]:
%%javascript
let student={
    name:"Preetha",
    age:20,
    Course:"COmputer"
}
for (let key in student){
  console.log(key,":",student[key]);
}

<IPython.core.display.Javascript object>

In [15]:
%%javascript
student={
  name:"Preetha",
  age:20,
  course:"Computer"
}
for (let key in student){
  console.log(key,":",student[key]);
}

<IPython.core.display.Javascript object>